### PR TITLE
Callback and interval cleared

### PR DESCRIPTION
**Pull request by citmusa**
With an optional callback function, and also clear the interval once final date is reached.

### CODE REVIEW

**Comment by nikhiln** [comment]
@citmusa can you please explain about this change?

**Comment by citmusa** [comment]
With the callback you can optionally pass a function to execute when the count down finishes.

**Comment by citmusa** [comment]
And at the end of count down the every second interval is cleared because it's no longer needed. It's for better performance.

**Comment by nikhiln** [comment]
Ok. Makes sense. Thanks.

**Pull request merged**
